# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logCLnormal_par <- function(beta, cov, block_y, block_x, m, n) {
    .Call(`_DIQIF_logCLnormal_par`, beta, cov, block_y, block_x, m, n)
}

eenormalmean_par <- function(beta, cov, block_y, block_x, m, n) {
    .Call(`_DIQIF_eenormalmean_par`, beta, cov, block_y, block_x, m, n)
}

GEEnormalmean_par <- function(beta, cov_inv, block_y, block_x, m, n) {
    .Call(`_DIQIF_GEEnormalmean_par`, beta, cov_inv, block_y, block_x, m, n)
}

GEEnormalderivmean_par <- function(cov_inv, block_y, block_x, m, n) {
    .Call(`_DIQIF_GEEnormalderivmean_par`, cov_inv, block_y, block_x, m, n)
}

eenormalderivmean_par <- function(cov, block_y, block_x, m, n) {
    .Call(`_DIQIF_eenormalderivmean_par`, cov, block_y, block_x, m, n)
}

psi_g_AR1derivvar_par <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call(`_DIQIF_psi_g_AR1derivvar_par`, beta, sigma, rho, block_y, block_x, m, n)
}

psi_g_CSderivvar_par <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call(`_DIQIF_psi_g_CSderivvar_par`, beta, sigma, rho, block_y, block_x, m, n)
}

psi_g_indderivvar_par <- function(beta, sigma, block_y, block_x, m, n) {
    .Call(`_DIQIF_psi_g_indderivvar_par`, beta, sigma, block_y, block_x, m, n)
}

eenormalCSvar_par <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call(`_DIQIF_eenormalCSvar_par`, beta, sigma, rho, block_y, block_x, m, n)
}

eenormalAR1var_par <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call(`_DIQIF_eenormalAR1var_par`, beta, sigma, rho, block_y, block_x, m, n)
}

eenormalindvar_par <- function(beta, sigma, block_y, block_x, m, n) {
    .Call(`_DIQIF_eenormalindvar_par`, beta, sigma, block_y, block_x, m, n)
}

increQIF_sub <- function(X, y, nobs, family, corstr, beta_old, maxit, tol) {
    .Call(`_DIQIF_increQIF_sub`, X, y, nobs, family, corstr, beta_old, maxit, tol)
}

QIF_eval <- function(X, y, nobs, family, corstr, beta_old) {
    .Call(`_DIQIF_QIF_eval`, X, y, nobs, family, corstr, beta_old)
}

getHessGrads <- function(y, x, offset, doffset, w, linkwave, zsca, zcor, corp, clusz, geestr, cor, par) {
    .Call(`_DIQIF_getHessGrads`, y, x, offset, doffset, w, linkwave, zsca, zcor, corp, clusz, geestr, cor, par)
}

